language: python
python:
  - "3.6"

addons:
  postgresql: "9.4"

services:
  - redis-server

#To install dependences
install:
  - pip install -r requirements.txt

before_script:
  - createuser kamaradeo --createdb
  - createdb flightbooking -U kamaradeo


#To run tests
script:
  - coverage run --source=flight_app manage.py test
  - coverage report -m

after_success:
  - coveralls