# Generated by Django 2.1.7 on 2019-03-11 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_auto_20190311_1609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tickets',
            name='status',
        ),
    ]
